### ISSUE TITLE
Migrate this repository to the Camunda Community Hub?

### ISSUE THREAD

**Issue by celanthe** [camunda-community-hub/zeebe-rust#32]
Hello! I hope today finds you well! My name is Rin Oliver, and I'm a Technical Community Builder at Camunda. I'm opening this issue today to ask if you might be interested in migrating this extension over to the [Camunda Community Hub](https://github.com/camunda-community-hub/community)?

We'd love to hear your feedback on how we might improve the overall community extension development process for maintainers and contributors moving forward, and learn more about what you'd like to see from this initiative in the future.

If migrating this extension something you'd be interested in, I can send you the instructions for doing so via email, or whatever communication method works best for you. 

Thank you so much for your time. I look forward to hearing from you.

**Comment by jtescher** [comment]
@celanthe happy to have this repo moved over if that's clearer for folks

**Comment by xomiamoore** [comment]
Hi @jtescher, I'll take over from @celanthe 👍  

I just invited you to the Camunda Community Hub as a member. Here are [instructions for transferring your repo to the Community Hub!](https://github.com/camunda-community-hub/community/blob/main/transferring-extensions.md) 

Let me know if you have any questions :)

**Comment by younes-io** [comment]
Has this repo been moved yet?

**Comment by xomiamoore** [comment]
Hey @younes-io! It has not, @jtescher or another maintainer would need to do the transfer. 

@jtescher Here if you need any assistance!

**Comment by younes-io** [comment]
Thanks for your feedback.
Just wanted to make sure this repo has a community behind it before starting contributions.
I prefer to wait until the transfer is made :)

**Comment by upachler** [comment]
Hi @jtescher, are there any news on this topic?

**Comment by jtescher** [comment]
hey @xomiamoore, looks like the invites expired. If you send them again I can move this over.

**Comment by xomiamoore** [comment]
Resent it @jtescher  :)

**Comment by jtescher** [comment]
Done

**Comment by xomiamoore** [comment]
Hooray! Thank you!
